apiVersion: v1
kind: Service
metadata:
  name: alpine-tty
  labels:
    lab: example
    system: client
    net: internal
spec:
  selector:
    lab: example
    system: client
    net: internal
  ports:
    - name: http
      port: 80
      targetPort: 1234

