apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop-deployment
  labels:
    lab: juice-shop
spec:
  selector:
    matchLabels:
      lab: juice-shop
  template:
    metadata:
      labels:
        lab: juice-shop
    spec:
      containers:
        - name: juice-shop
          image: bkimminich/juice-shop
          ports:
            - containerPort: 3000
