apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali-server
  labels:
    app: ssh-server
    lab: initial
spec:
  selector:
    matchLabels:
      app: ssh-server
  template:
    metadata:
      labels:
        app: ssh-server
        lab: initial
    spec:
      containers:
        - name: ssh-server
          image: kali-server
          imagePullPolicy: Never
          ports:
            - containerPort: 22
            - containerPort: 80
