apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali-client
  labels:
    app: ssh-client
    lab: initial
spec:
  selector:
    matchLabels:
      app: ssh-client
  template:
    metadata:
      labels:
        app: ssh-client
        lab: initial
    spec:
      containers:
        - name: ssh-client
          image: kali-client
          imagePullPolicy: Never
          ports:
            - containerPort: 22
            - containerPort: 80
