apiVersion: apps/v1
kind: Deployment
metadata:
  name: kali-client
  labels:
    lab: example
    system: client
    net: internal
spec:
  selector:
    matchLabels:
      lab: example
      system: client
      net: internal    
  template:
    metadata:
      labels:
        lab: example
        system: client
        net: internal
    spec:
      containers:
        - name: kali-vnc
          image: deep1807/kali-gui
          ports:
            - containerPort: 1234
            - containerPort: 6080



